Order list page & Order create modal
AzurIce/HeavyPlatform pull request #14
Opened 2024-06-09 10:25 UTC by FooLiqi

Order list page & Order create modal

2024-06-09 18:21 UTC, AzurIce requested changes

2024-06-09 18:21 UTC, AzurIce commented on frontend/src/components/OrderModal.tsx
> +    setStep(step() + 1);
这里可以写成 `setStep(v => v+1)`，下面同理

2024-06-09 18:21 UTC, AzurIce commented on frontend/src/components/OrderModal.tsx
> +              感谢您的购买喵~ 💖 小猫娘会尽快处理您的订单喵~ 💖
🤤可爱小猫娘

2024-06-09 18:21 UTC, AzurIce commented on frontend/src/lib/store.ts
> +}, "deleteCartItem");
这些不用再单独封了，只需要在调用api之后调用一下revalidate(getCartItems.key)和revalidate(getCartItem.keyFor(id))就好，然后cache包裹的缓存就会被标记失效，对应的createAsync就会重新获取数据，
参考这里的写法：https://github.com/AzurIce/HeavyPlatform/blob/main/frontend%2Fsrc%2Fpages%2FAdmin%2FMain%2FGood%2Fcomponents%2FCreateGoodModal.tsx#L37-L52

2024-06-09 18:22 UTC, FooLiqi commented on frontend/src/lib/store.ts
> +}, "deleteCartItem");
Sir yes sir!

2024-06-09 18:26 UTC, FooLiqi commented on frontend/src/lib/store.ts
> +}, "deleteCartItem");
ok我删了。其实这两个我也没用到，根本就没新加购物车啊哈哈哈，笑死

2024-06-10 08:05 UTC, AzurIce requested changes

2024-06-10 08:05 UTC, AzurIce commented on frontend/src/lib/store.ts
> +}, "deleteCartItem");
笑死，下面那个 order 也是

2024-06-10 08:05 UTC, AzurIce commented on frontend/src/lib/store.ts
> +
这块也是（）

2024-06-10 08:32 UTC, FooLiqi commented on frontend/src/lib/store.ts
> +
got it

2024-06-10 15:56 UTC, AzurIce approved these changes

2024-06-10 15:56 UTC, merged